### PR TITLE
Fixing error code for missing args

### PR DESCRIPTION
**Pull request by pnevares**
ERR_SERVER seemed incorrect here, but please let me know if I'm wrong.

### CODE REVIEW

**Comment by electroly** [comment]
This one's a little rough.  The reason it said "(Temporary)" is that this method isn't following the published documentation.  The API docs say nothing about requiring a search term, author, or parent author; you're supposed to be able to search by just a post category alone.  But NuSearch is often too slow to actually be usable, so I don't use it for /v2/search; instead I use the Shack search and massage the results.  The Shack search doesn't support searching by just post category (even though NuSearch does), hence this undocumented error.  I think a better fix might be to revert to NuSearch when a category-only search is made, rather than giving an error.  I'll take a look at this tonight or tomorrow night.

**Comment by electroly** [comment]
I haven't forgotten about this, I'm just super lazy.

**Comment by pnevares** [comment]
Be as lazy as you want, it's a small thing.

**Comment by electroly** [comment]
No longer needed; /v2/search uses NuSearch now and you can do post category-only searches.

**Pull request closed without merging**
